name: Generate EPG (WebGrab++)

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  epg:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Prepare WebGrab home
        run: |
          mkdir -p ~/.wg++
          cp -r WebGrabPlus_5.5/.wg++/* ~/.wg++

      - name: Copy siteini & channels
        run: |
          mkdir -p ~/.wg++/siteini.pack
          cp webgrab/siteini.pack/*.ini ~/.wg++/siteini.pack/
          cp webgrab/channels/*.xml ~/.wg++/

      - name: Run WebGrab++
        run: |
          chmod +x ~/.wg++/run.net.sh
          cd ~/.wg++
          ./run.net.sh

      - name: Commit EPG
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add *.xml || true
          git commit -m "Update EPG" || true
          git push || true
