name: Grab EPG

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"   # مرة يوميًا

jobs:
  grab:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y mono-complete wget tar

      - name: Download WebGrab+Plus (latest)
        run: |
          wget https://github.com/SilentButeo2/webgrabplus/raw/master/WebGrabPlus_latest_install.tar.gz
          tar -xzf WebGrabPlus_latest_install.tar.gz

      - name: Prepare WebGrab files
        run: |
          mkdir -p WebGrab+Plus/bin/output
          cp webgrab/WebGrab++.config.xml WebGrab+Plus/bin/
          cp webgrab/channels/*.xml WebGrab+Plus/bin/
          cp -r webgrab/siteini.pack WebGrab+Plus/bin/

      - name: Run WebGrab+Plus
        run: |
          cd WebGrab+Plus/bin
          mono WebGrab+Plus.exe

      - name: Commit EPG
        run: |
          if [ -f WebGrab+Plus/bin/output/guide.xml ]; then
            git config --global user.name "github-actions"
            git config --global user.email "actions@github.com"
            git add WebGrab+Plus/bin/output/guide.xml
            git commit -m "Auto update EPG" || echo "No changes"
            git push
          else
            echo "EPG not generated"
            exit 1
          fi
