name: WebGrab EPG

on:
  workflow_dispatch:

jobs:
  grab:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y libcurl4 libicu-dev

      - name: Extract WebGrab++
        run: |
          mkdir -p .wg++
          tar -xzf WebGrabPlus_5.5_install.tar.gz --strip-components=1 -C .wg++

      - name: Copy config and site files
        run: |
          cp webgrab/WebGrab++.config.xml .wg++
          cp webgrab/channels/*.xml .wg++
          cp webgrab/siteini.pack/*.ini .wg++

      - name: Fix permissions
        run: |
          chmod +x .wg++/run.net.sh

      - name: Run WebGrab++
        run: |
          cd .wg++
          ./run.net.sh

      - name: Commit EPG
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add epg.xml
          git commit -m "Update EPG" || echo "No changes"
          git push
